=== cambridge-cares/TheWorldAvatar/obsolete/PWServlet_OWL/Sim1/Working_dir/MoDS_inputs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://como.cheng.cam.ac.uk/MoDS" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mods">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="algorithms">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="algorithm">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="detail">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="name" type="xs:string" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="cases">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="case">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="detail">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="name" type="xs:string" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="files">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="file">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="detail">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="name" type="xs:string" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="file_name" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="functions" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="function">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="details">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="detail">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="name" type="xs:string" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="usage" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="parameter">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="scaling" type="xs:string" />
                    <xs:element name="cases">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" name="case" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="files">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="initial_read">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="details">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="detail">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute name="name" type="xs:string" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="file_name" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="working_read">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="details">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="detail">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute name="name" type="xs:string" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="file_name" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="working_write">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="details">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element maxOccurs="unbounded" name="detail">
                                        <xs:complexType>
                                          <xs:simpleContent>
                                            <xs:extension base="xs:string">
                                              <xs:attribute name="name" type="xs:string" use="required" />
                                            </xs:extension>
                                          </xs:simpleContent>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                              <xs:attribute name="file_name" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="required" />
                  <xs:attribute name="subtype" type="xs:string" use="required" />
                  <xs:attribute name="case_detail_sep" type="xs:string" use="optional" />
                  <xs:attribute name="detail_sep" type="xs:string" use="optional" />
                  <xs:attribute name="n_params_per_case" type="xs:string" use="optional" />
                  <xs:attribute name="name" type="xs:string" use="optional" />
                  <xs:attribute name="name_suffix_detail" type="xs:string" use="optional" />
                  <xs:attribute name="preserve_white_space" type="xs:string" use="optional" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== cambridge-cares/TheWorldAvatar/Agents/MoDSSimpleAgent/mods-simple-agent/src/main/resources/MoDS_inputs_templates/SampleSRM.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods xsi:schemaLocation="http://como.cheng.cam.ac.uk/MoDS MoDS_inputs.xsd" xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <algorithms>
        <algorithm name="Initial" display_name="HIDDEN">
            <details>
                <detail name="algorithm_type">Initial</detail>
                <detail name="optimisable_param_subtypes"></detail>
                <detail name="response_param_subtypes"></detail>
                <detail name="global">false</detail>
            </details>
        </algorithm>
        <algorithm name="SamplingAlg" display_name="Model [Evaluations]">
            <details>
                <detail name="algorithm_type">Read_previous</detail>
                <detail name="model_name">exe</detail>
                <detail name="objective_function">SumOfSquares</detail>
                <detail name="output_by_case">false</detail>
                <detail name="output_values">true</detail>
                <detail name="global">false</detail>
                <detail name="evaluate_models">true</detail>
				<detail name="previous_algorithm">SamplingAlg_data</detail>
            </details>
        </algorithm>
    </algorithms>
    <models></models>
    <cases></cases>
    <files></files>
    <parameters></parameters>
</mods>

=== cambridge-cares/TheWorldAvatar/Agents/MoDSSimpleAgent/mods-simple-agent/src/main/resources/MoDS_inputs_templates/MOOonly_HDMR.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods
    xsi:schemaLocation="http://como.cheng.cam.ac.uk/MoDS MoDS_inputs.xsd"
    xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <algorithms>
        <algorithm name="Initial" display_name="HIDDEN">
            <details>
                <detail name="algorithm_type">Initial</detail>
                <detail name="optimisable_param_subtypes"></detail>
                <detail name="response_param_subtypes"></detail>
                <detail name="global">false</detail>
            </details>
        </algorithm>
        <algorithm name="GenSurrogateAlg" display_name="Surrogate model">
            <details>
                <detail name="algorithm_type">Surrogate</detail>
                <detail name="global">false</detail>
                <detail name="surrogate_type">HDMR</detail>
                <detail name="fit_to_coded_responses">false</detail>
                <detail name="order">6</detail>
                <detail name="HDMRorder">2</detail>
                <detail name="r_squared_tol">0.99999</detail>
                <detail name="previous_algorithm">Initial</detail>
            </details>
        </algorithm>
        <algorithm name="MOOAlg" display_name="Model [Optimised]">
            <details>
                <detail name="model_name">GenSurrogateAlg</detail>
                <detail name="output_by_case">false</detail>
                <detail name="output_values">true</detail>
                <detail name="constrained">true</detail>
                <detail name="pymoo:save_history">false</detail>
                <detail name="pymoo:seed">0</detail>
                <detail name="pymoo:verbose">false</detail>
                <detail name="pymoo:eliminate_duplicates">true</detail>
                <detail name="pymoo:min_infeas_pop_size">0</detail>
                <detail name="pymoo:n_offsprings">10</detail>
                <detail name="pymoo:pop_size">30</detail>
                <detail name="pymoo:ref_dirs:name">energy</detail>
                <detail name="pymoo:ref_dirs:n_points">50</detail>
                <detail name="previous_algorithm">Initial</detail>
                <detail name="pymoo:algorithm_type">unsga3</detail>
                <detail name="algorithm_type">PyMOO</detail>
            </details>
        </algorithm>
    </algorithms>
    <models></models>
    <cases></cases>
    <files></files>
    <parameters></parameters>
</mods>

=== cambridge-cares/TheWorldAvatar/Agents/MoDSSimpleAgent/mods-simple-agent/src/main/resources/MoDS_inputs_templates/Sensitivity_HDMR.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods xsi:schemaLocation="http://como.cheng.cam.ac.uk/MoDS MoDS_inputs.xsd" xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <algorithms>
        <algorithm name="Data_Algorithm" display_name="Base data for surrogate model">
            <details>
                <detail name="algorithm_type">Read_previous</detail>
                <detail name="output_values">false</detail>
                <detail name="previous_algorithm">Data_Algorithm</detail>
            </details>
        </algorithm>
        <algorithm name="GenSurrogateAlg" display_name="Surrogate model">
            <details>
                <detail name="algorithm_type">Surrogate</detail>
                <detail name="global">false</detail>
                <detail name="surrogate_type">HDMR</detail>
                <detail name="fit_to_coded_responses">false</detail>
                <detail name="order">6</detail>
                <detail name="HDMRorder">2</detail>
                <detail name="r_squared_tol">0.99999</detail>
                <detail name="previous_algorithm">Data_Algorithm</detail>
            </details>
        </algorithm>
    </algorithms>
    <models></models>
    <cases></cases>
    <files></files>
    <parameters></parameters>
</mods>

=== cambridge-cares/TheWorldAvatar/Agents/MoDSSimpleAgent/mods-simple-agent/src/main/resources/MoDS_inputs_templates/Evaluate_DKL.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods
    xsi:schemaLocation="http://como.cheng.cam.ac.uk/MoDS MoDS_inputs.xsd"
    xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <algorithms>
        <algorithm name="Initial" display_name="HIDDEN">
            <details>
                <detail name="algorithm_type">Initial</detail>
                <detail name="optimisable_param_subtypes"></detail>
                <detail name="response_param_subtypes"></detail>
                <detail name="global">false</detail>
            </details>
        </algorithm>
        <algorithm name="GenSurrogateAlg" display_name="HIDDEN">
            <details>
                <detail name="algorithm_type">Surrogate</detail>
                <detail name="global">false</detail>
                <detail name="surrogate_type">AutotunedDKL</detail>
                <detail name="fit_to_coded_responses">false</detail>
                <detail name="pythonfilename">surrogate-torch-DKL</detail>
                <detail name="python_arch">100,5,1</detail>
                <detail name="python_kernel">RBF</detail>
                <detail name="python_wnoscale">0.1</detail>
                <detail name="python_numepochs">10</detail>
                <detail name="python_lr">0.001</detail>
                <detail name="validation_set_fraction">0.1</detail>
                <detail name="rng_seed">5489</detail>
                <detail name="global_search_seed">1</detail>
                <detail name="global_search_n_points">10</detail>
                <detail name="opti_algorithm_type">Hooke_Jeeves</detail>
                <detail name="opti_n_iters">50</detail>
                <detail name="opti_n_initial_points">1</detail>
                <detail name="opti_constrained">true</detail>
                <detail name="opti_rho">0.5</detail>
                <detail name="opti_rho_factor">0.5</detail>
                <detail name="opti_epsilon">0.001</detail>
                <detail name="previous_algorithm">Initial</detail>
            </details>
        </algorithm>
        <algorithm name="SamplingAlg" display_name="Surrogate model [Evaluations]">
            <details>
                <detail name="algorithm_type">Read_previous</detail>
                <detail name="model_name">GenSurrogateAlg</detail>
                <detail name="objective_function">SumOfSquares</detail>
                <detail name="output_by_case">false</detail>
                <detail name="output_values">true</detail>
                <detail name="global">false</detail>
                <detail name="evaluate_models">true</detail>
                <detail name="previous_algorithm">SamplingAlg_data</detail>
            </details>
        </algorithm>
    </algorithms>
    <models></models>
    <cases></cases>
    <files></files>
    <parameters></parameters>
</mods>

=== cambridge-cares/TheWorldAvatar/Agents/MoDSSimpleAgent/mods-simple-agent/src/main/resources/MoDS_inputs_templates/Evaluate.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods xsi:schemaLocation="http://como.cheng.cam.ac.uk/MoDS MoDS_inputs.xsd" xmlns="http://como.cheng.cam.ac.uk/MoDS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <algorithms>
        <algorithm name="Initial" display_name="HIDDEN">
            <details>
                <detail name="algorithm_type">Initial</detail>
                <detail name="optimisable_param_subtypes"></detail>
                <detail name="response_param_subtypes"></detail>
                <detail name="global">false</detail>
            </details>
        </algorithm>
        <algorithm name="GenSurrogateAlg" display_name="Surrogate model">
            <details>
                <detail name="algorithm_type">Surrogate</detail>
                <detail name="global">false</detail>
                <detail name="surrogate_type">HDMR</detail>
                <detail name="fit_to_coded_responses">false</detail>
                <detail name="order">6</detail>
                <detail name="HDMRorder">2</detail>
                <detail name="r_squared_tol">0.99999</detail>
                <detail name="previous_algorithm">Initial</detail>
            </details>
        </algorithm>
        <algorithm name="SamplingAlg" display_name="Surrogate model [Evaluations]">
            <details>
                <detail name="algorithm_type">Read_previous</detail>
                <detail name="model_name">GenSurrogateAlg</detail>
                <detail name="objective_function">SumOfSquares</detail>
                <detail name="output_by_case">false</detail>
                <detail name="output_values">true</detail>
                <detail name="global">false</detail>
                <detail name="evaluate_models">true</detail>
                <detail name="previous_algorithm">SamplingAlg_data</detail>
            </details>
        </algorithm>
    </algorithms>
    <models></models>
    <cases></cases>
    <files></files>
    <parameters></parameters>
</mods>
